### ISSUE TITLE
Bug NO log out button after logging in 

### ISSUE THREAD

**Issue by govindumeesala** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#102]
# Issue Report

## Description

No log out button present in the navbar once user logged in 

## Steps to Reproduce the Issue

To assist us in understanding and resolving the issue, please outline the steps you took that led to the problem:

1. **Action 1:** log in to the website 
2. **Action 2:** You will see no log out button

## Expected Behavior

Log out button should be in navbar to allow users to log out

## Actual Behavior

No log out option available

## Screenshots (if applicable)

![image](https://github.com/user-attachments/assets/03ab96cb-3a15-41f6-ba37-eeb823278717)

@saurabhbakolia  @thakuratul2  assign this to me

**Comment by thakuratul2** [comment]
@govindumeesala assigned

**Comment by govindumeesala** [comment]
@thakuratul2 kindly consider this
# Please take a note :
## The program managers mentioned that all prs and issues must have not have dashes "-" in the level labels 
## remove level-1 and 
## add level1
## since they mentioned if dashes are added then not counted
