### ISSUE TITLE
Google Authorization using Firebase

### ISSUE THREAD

**Issue by samriddhitiwary** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#108]
# Issue Report

## Title
Google Authorization using Firebase

## Description
I would like to request the addition of Google Authorization using Firebase in our project. This feature would allow users to authenticate using their Google accounts, streamlining the sign-in process and enhancing user experience. Firebase provides a robust authentication solution that can simplify the integration of Google Sign-In, making it easier for users to access the application without having to create a new account or remember another password.

## Steps to Reproduce the Issue
Action 1: Navigate to the login page of the application.
Action 2: Click on the "Sign in with Google" button.
Action 3: Select a Google account from the prompt and attempt to authenticate.
*Feel free to be as detailed as necessary so we can replicate the issue accurately.*

## Expected Behavior

When the above steps are followed, I expected that:

The user would be successfully authenticated via Google and redirected to their dashboard.
The user's profile information (name, email) would be retrieved and displayed in the application.

## Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/57c34af4-d307-4c37-9c08-1d0482f00c0b)

---

**Comment by samriddhitiwary** [comment]
@thakuratul2 Could you please assign this issue to me under the gssoc-ext and hacktoberfest label

**Comment by saurabhbakolia** [comment]
@samriddhitiwary assigned!

**Comment by samriddhitiwary** [comment]
@saurabhbakolia thank you

**Comment by samriddhitiwary** [comment]
@saurabhbakolia and @thakuratul2  I have created the PR could you please review it
