### ISSUE TITLE
[Feature]: Imlimenting clickable contact info. 

### ISSUE THREAD

**Issue by Amarjha01** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#11]
#New Feature

## Title
clickable link to footer contect section.

## Description
clickable link to footer contect section so that user can easily navigate or view location and when user click on email that will redirect to mail 

## Steps to Implement 

1 . using google map API .
2. using  mailto protocol

@thakuratul2 @saurabhbakolia

**Comment by Amarjha01** [comment]
@thakuratul2 hello sir could you please assign me I want to implement this feature and also please add labels.

**Comment by Amarjha01** [comment]
> @thakuratul2 hello sir can you please assign me I want to implement this feature and also please add labels.

**Comment by Amarjha01** [comment]
@thakuratul2 Are you there sir ?

**Comment by thakuratul2** [comment]
@Amarjha01 yes please edit the proper title of the issue

**Comment by thakuratul2** [comment]
@Amarjha01 new feature is not accepting

**Comment by Amarjha01** [comment]
thank you sir

**Comment by thakuratul2** [comment]
@Amarjha01 please edit the name of title

**Comment by Amarjha01** [comment]
<img width="932" alt="image" src="https://github.com/user-attachments/assets/1d2520cf-e38b-455b-910c-7a1e6115ac2f">
it's taking time because i am getting this inconsistency in path . the actual folder starts with capital where as in path it's small later so first I will resolve this then imliment other feature.

**Comment by Amarjha01** [comment]
<img width="907" alt="image" src="https://github.com/user-attachments/assets/abf30859-5cda-46a2-befc-519a3aed0f9c">
sir please guide me why my pull request merged is not showing here ?

**Comment by thakuratul2** [comment]
@Amarjha01 click on the closed option in the pull request

**Comment by Amarjha01** [comment]
<img width="954" alt="image" src="https://github.com/user-attachments/assets/b522d015-55b0-4442-8eeb-cb2ee24f1828">
sir the code is not merged in master branch

**Comment by thakuratul2** [comment]
@Amarjha01 please checkout to develop branch

**Comment by thakuratul2** [comment]
@Amarjha01 i already tell that develop branch is the main

**Comment by Amarjha01** [comment]
@thakuratul2  sir can you please close this issue manually because I had not mentioned issue no this was my first PR in open Source.

**Comment by Amarjha01** [comment]
@thakuratul2 @saurabhbakolia sir can you please change the level-3 to level3 because it's not counted in leader board.
