### ISSUE TITLE
When you add a product to the cart, then your product count shows in the navbar  how many products you add to the cart. 

### ISSUE THREAD

**Issue by RockySheoran** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#110]
# Issue Report
When you add a product to the cart, then your product count shows in the navbar  how many products you add to the cart. 

## Title
Add product in cart navbar 
[Provide a concise title for the issue]

## Description

when we are select any product and add to product to the cart and then product show the navbar card title .
On the other side, I have used the same function in my practice website, and I want to solve the problem in a few days.

So you will see this website: " https://e-commerce-project-rs.netlify.app/ ". What i want say. 
Can you assignee me this issue 
@saurabhbakolia

**Comment by saurabhbakolia** [comment]
@RockySheoran assigned!

**Comment by RockySheoran** [comment]
thanks Bhai
