### ISSUE TITLE
Bug: full image is not showing in the slider in mobile,macs and ipad 

### ISSUE THREAD

**Issue by adityalaxkar123** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#132]
Title: bug 

Description: in mobile,macs and ipad slider not show the full image of product 

Screenshot of bug:
![IMG_20241007_133545](https://github.com/user-attachments/assets/0532dd1b-2f4d-4aa3-81a4-c48f940abf41)

About me: a GSSOC'24 extended member

**Comment by adityalaxkar123** [comment]
Can you assign it to me under GSSOC'24 extended member

**Comment by saurabhbakolia** [comment]
@adityalaxkar123 assigned!
