### ISSUE TITLE
Footer Improvement

### ISSUE THREAD

**Issue by Rizvi-Faiz** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#14]
# Footer Improvement

## Issue Overview

The current footer design lacks functionality and visual appeal, which can detract from the overall user experience. This section outlines suggested improvements for enhancing the footer.

## Current Limitations

- **Limited Information:** The footer currently contains minimal information, making it less informative for users.
- **Visual Design:** The design is outdated and does not align with modern UI standards, reducing engagement.
- **Accessibility Issues:** There may be issues with text contrast and clarity, affecting usability for all users.

### 1. Expand Footer Content
- **Description:** Include additional information such as links to privacy policies, terms of service, and contact information.
- **Expected Outcome:** Users have quick access to important information without navigating away from the page.

### 2. Modernize Visual Design
- **Description:** Update the footer’s visual elements, including colors, fonts, and layout, to align with current design trends.
- **Expected Outcome:** The footer should have a cohesive look that complements the overall application design.

### 3. Add Social Media Links
- **Description:** Include icons linking to the project's social media profiles (e.g., Twitter, Facebook, LinkedIn).
- **Expected Outcome:** Users can easily connect with the project on social media, increasing engagement and visibility.

### 4. Ensure Accessibility
- **Description:** Optimize the footer for accessibility by ensuring sufficient contrast and using semantic HTML elements.
- **Expected Outcome:** All users, including those with disabilities, can navigate the footer easily.

## Steps to Reproduce Current Issues

1. Open the application and scroll to the footer section.
2. Observe the limited information provided and assess the visual appeal.
3. Evaluate accessibility by checking color contrast and clarity.

## Screenshots

![image](https://github.com/user-attachments/assets/484fbdb1-2644-4503-8621-561313d73a21)
---

@thakuratul2 can you please assign this to me under gssoc-ext and hacktoberfest and also give a level

**Comment by thakuratul2** [comment]
@Rizvi-Faiz Assigned and create the Proper PR

**Comment by samriddhitiwary** [comment]
Hi @Rizvi-Faiz could you please assign this to me

**Comment by thakuratul2** [comment]
@samriddhitiwary already assigned create new issue

**Comment by saurabhbakolia** [comment]
Closing this issue as it's fixed in PR #116 .
