### ISSUE TITLE
Create ADMIN page to CREATE, READ, UPDATE, and DELETE Products into MongoDB using existing CRUD API

### ISSUE THREAD

**Issue by samriddhitiwary** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#165]
# Issue Report

## Title

Create ADMIN page to CREATE, READ, UPDATE, and DELETE Products into MongoDB using existing CRUD API

## Description
This issue involves building an Admin page that allows for the Create, Read, Update, and Delete (CRUD) operations on Products stored in MongoDB. The page will interact with an existing CRUD API for product management. The page should include a form for product creation and editing, a table to display all products, and functionality to delete products.

## Steps to Reproduce the Issue
Action 1: Set up the admin page with components such as a form for product creation and a table for displaying products.
Action 2: Implement the connection to the existing CRUD API for fetching, creating, updating, and deleting products in MongoDB.
Action 3: Add functionality to handle user inputs for creating new products and updating existing ones.
Action 4: Test the form and table components to ensure proper data flow between the frontend and backend.

## Expected Behavior

Products should be created, displayed, updated, and deleted through the admin page.
The admin should be able to perform these operations by interacting with the form and table, and changes should reflect in the MongoDB database.
Data validation errors should be handled properly.

---

Thank you for taking the time to report this issue! We appreciate your help in improving our project.

**Comment by samriddhitiwary** [comment]
@thakuratul2 Could you please assign this issue to me under gssoc-ext and hacktoberfest

**Comment by instantboostbyabhaykeshari** [comment]
@saurabhbakolia Please assign this issue to me

**Comment by thakuratul2** [comment]
@samriddhitiwary assigned

**Comment by samriddhitiwary** [comment]
@thakuratul2 Thank you I will start working on it

**Comment by thakuratul2** [comment]
@samriddhitiwary status?

**Comment by samriddhitiwary** [comment]
@thakuratul2 Yes I am working on it

**Comment by samriddhitiwary** [comment]
@thakuratul2 Please give me a couple of days

**Comment by instantboostbyabhaykeshari** [comment]
@thakuratul2  Working

**Comment by thakuratul2** [comment]
@samriddhitiwary oky

**Comment by vikas83pal** [comment]
@saurabhbakolia please assign me this issue

**Comment by samriddhitiwary** [comment]
@thakuratul2 @saurabhbakolia I will finish it by tomorrow

**Comment by thakuratul2** [comment]
@samriddhitiwary asap please

**Comment by samriddhitiwary** [comment]
@thakuratul2 Yes

**Comment by thakuratul2** [comment]
@samriddhitiwary any update can you done it

**Comment by samriddhitiwary** [comment]
@thakuratul2 Yes the crud operation is done, I am just making the UI a bit better by today I will raise the PR

**Comment by saurabhbakolia** [comment]
Closing as resolved in PR #258
