### ISSUE TITLE
[Improvement] : Scroll Button To Inhance User Experience

### ISSUE THREAD

**Issue by Amarjha01** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#168]
## Description
Button which will scroll user page from bottom to top.

## Steps to Reproduce the Issue

1. **Action 1:** Create Small Button at bottom of the page.
2. **Action 2:** I'll point this button to the top of page using ID.

@thakuratul2 @saurabhbakolia Sir, I would like to work on this

**Comment by thakuratul2** [comment]
@Amarjha01 assigned
