### ISSUE TITLE
Add Pull Request MD file into README md

### ISSUE THREAD

**Issue by thakuratul2** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#18]
## Description 

Please add the pull request md into the README file and make the link clickable.  

##Create the branch from the develop and give the pull request to the develop branch only

**Comment by Rizvi-Faiz** [comment]
Sir i did add the Pull Request in Read me file

**Comment by Charul00** [comment]
can you please assign to me

**Comment by Charul00** [comment]
can you please assign to me

**Comment by thakuratul2** [comment]
@Rizvi-Faiz you created the wrong PR i want pull request content open and PR md is already their

**Comment by thakuratul2** [comment]
@Charul00 assign
