### ISSUE TITLE
Proposal of Creating a Coming Soon Page

### ISSUE THREAD

**Issue by coder-writes** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#186]
# Issue Report

## Title
Proposal of Creating a Cooming Soon Page
## Description
There Are many Section in the Websties which are not fully Functional,there are many buttons, hyperlinks, and all which are not functional so we can create a Common Page for all Such elements in the page and then redirect all the elements to the same page as it will Create Positive Impact on the Users of the Web site . The Website Will feel Like Broken.

## Steps to Reproduce the Issue

1. **Action 1:** Make  a Coming Soon Page for all the upcoming Features
2. **Action 2:** Identify all the elements in the page that are not present now.
3. **Action 3:** Redirect all the elements to the same page

## Expected Behavior

![Screenshot 2024-10-12 140702](https://github.com/user-attachments/assets/dc27c6bd-74dd-4185-b9ea-e5f473a5b50f)

## Actual Behavior

doing nothing

**Comment by vikas83pal** [comment]
@saurabhbakolia please assign me this issue i love to contribute

**Comment by SatyamTiwari069** [comment]
Add labels and please assign me the task as for gssoc24 extd

**Comment by coder-writes** [comment]
hey @saurabhbakolia Please assign this task to me under the tag Gssoc Extd and suitable level.I will Submit my work within the 4-5 hours of assigning.

**Comment by coder-writes** [comment]
hey @saurabhbakolia  please look into the issue actively

**Comment by thakuratul2** [comment]
@coder-writes assigned

**Comment by saurabhbakolia** [comment]
Closing as issue resolved in PR #243

**Comment by coder-writes** [comment]
@saurabhbakolia Please rethink about the level as coming soon page is to be created from the scratch.
