### ISSUE TITLE
Add Google OAuth for Login/Registration Page

### ISSUE THREAD

**Issue by Lokesh-Bijarniya** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#188]
# Issue Report

Currently, users are required to create a new account by filling out a registration form, which often involves providing an email address, creating a password, and confirming the account. This process can be cumbersome and frustrating for users, leading to potential abandonment of the registration process. Additionally, users often struggle to remember passwords, and accounts may be created with invalid email addresses, impacting overall user satisfaction and engagement with the platform.

## Title

Add Google OAuth for Login/Registration Page

## Description

I propose integrating Google OAuth authentication into the login and registration process. Users would have the option to log in or sign up using their existing Google accounts. This would involve adding a "Sign in with Google" button on the login/register page that redirects users to Google’s authentication flow. Upon successful authentication, users would be granted access to the platform without needing to input additional credentials. This solution would streamline the registration process and enhance user convenience.

## Steps to Reproduce the Issue

1. **Access the Login Page:**  Navigate to the login page of the platform.
2. **Observe Current Registration Process:** Note the requirement to fill out the registration form, including entering an email address, creating a password, and confirming the account.
3. **Identify User Frustrations:** Try to register for an account and observe any difficulties or frustrations encountered, such as the need to remember a password or validate the email address.

## Expected Behaviour

When users visit the login/registration page, they should see an option to sign up or log in using their Google account, represented by a "Sign in with Google" button. Upon clicking this button, users should be redirected to Google's authentication page, and after successful login, they should be directed back to the platform seamlessly.

## Actual Behaviour

Currently, users must complete a traditional form without a streamlined option for logging in or registering with Google. This can lead to abandonment of the process due to password management issues and concerns about using valid email addresses.

## Screenshots (if applicable)

N/A

## Additional Context

Implementing Google OAuth could significantly improve user experience by reducing friction in the registration and login processes. It would help in decreasing the number of abandoned registrations due to cumbersome form-filling and password management issues.

Thank you for considering this proposal to enhance our platform's authentication process! We appreciate your efforts in improving user experience.

**Comment by thakuratul2** [comment]
@Lokesh-Bijarniya not needed it already done
