### ISSUE TITLE
Hacktoberfest Topic: GSSOC Extended - Program Manager 🟡

### ISSUE THREAD

**Issue by MastanSayyad** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#191]
Hi @saurabhbakolia 

You are using `hacktoberfest-accepted` label in your PR
Make sure you add `hacktoberfest` topic in the description of your project

![image](https://github.com/user-attachments/assets/c0eeb278-6e12-48fe-b2f2-ef5b9cc2340a)

**Comment by thakuratul2** [comment]
@saurabhbakolia please mention this
