### ISSUE TITLE
Add Google Authentication to Register and Sign In Buttons

### ISSUE THREAD

**Issue by Laxmi01345** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#193]
# Issue Report 

## Title

Add Google Authentication to Register and Sign In Buttons

## Description

The current user registration and sign-in forms only allow for manual account creation and login using email, username, and password. To improve user experience and streamline the authentication process, we need to add Google Authentication functionality. This feature will allow users to sign in or register using their Google accounts. The functionality should be added to both the "Create" button on the registration form and the "Login" button for existing users.

## Steps to Reproduce the Issue

To assist us in understanding and resolving the issue, please outline the steps you took that led to the problem:

1. **Action 1:** Navigate to the registration page (or sign-in page).
2. **Action 2:** Describe the second action you took.
3. **Action 3:** Observe that there is no option for Google Authentication.

## Expected Behavior

The user should have the option to register and sign in using their Google account by clicking a "Sign in with Google" button.

## Actual Behavior
There is currently no option for Google Authentication. The user can only register or sign in by manually entering their credentials.

## Project Tags:
 gssoc-ext , Hacktoberfest.

**Comment by Laxmi01345** [comment]
I want to work on this issue .

**Comment by thakuratul2** [comment]
@Laxmi01345 already done this issue
