### ISSUE TITLE
Password Recovery Feature

### ISSUE THREAD

**Issue by saras-69** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#201]
![Screenshot 2024-10-15 022439](https://github.com/user-attachments/assets/cfeab05e-dbec-4b7e-9992-6a776113828d)
Description
We need to implement a password recovery feature that allows users to reset their passwords if they forget them. This feature should include an option to send a password reset link to the user's registered email address.

Steps to Reproduce the Issue
To assist us in understanding and resolving the issue, please outline the steps you took that led to the problem:

Action 1: Navigate to the login page.
Action 2: Click on the "Forgot Password?" link.
Action 3: Enter the registered email address to receive the reset link.
Feel free to be as detailed as necessary so we can replicate the issue accurately.

Expected Behavior
Users should receive an email with a link to reset their password, allowing them to create a new password successfully.

Actual Behavior
Currently, there is no password recovery option available on the login page.

Additional Context
Adding a password recovery feature is crucial for improving user experience and security. It will ensure that users can regain access to their accounts without requiring admin assistance.
![Screenshot 2024-10-02 140727](https://github.com/user-attachments/assets/ad4edf5d-cf03-432e-b205-c83a81b6070e)
![Screenshot 2024-10-13 235803](https://github.com/user-attachments/assets/a77ec993-ec15-401f-85a9-6a9f32cc9fe8)

**Comment by thakuratul2** [comment]
@saras-69 done

**Comment by saurabhbakolia** [comment]
Closing this issue as resolved in PR #232
