### ISSUE TITLE
Add outline around input fields in register and login forms

### ISSUE THREAD

**Issue by sezallagwal** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#203]
# Issue Report

## Title

Add outline around input fields in register and login forms

## Description

The form fields for in the register and login forms do not have a visible outline, which makes it less clear where the focus is. This issue affects user experience as it's difficult to visually identify the active field.
## Steps to Reproduce the Issue

To assist us in understanding and resolving the issue, please outline the steps you took that led to the problem:

1. **Action 1:** Go to the register or login page.
2. **Action 2:** Observe the input fields for username and password.
3. **Action 3:** Focus on one of the fields by clicking or tabbing into it.

*Feel free to be as detailed as necessary so we can replicate the issue accurately.*

## Expected Behavior

The username and password input fields should have a visible outline or border when focused, making them stand out and providing clear visual feedback to the user.

## Actual Behavior

The input fields for username and password do not have an outline or border, which makes it difficult to determine where the user's focus is when filling out the form.

## Screenshots (if applicable)

![image](https://github.com/user-attachments/assets/b0e5e493-8d70-45fe-907c-841ac222f052)
![image](https://github.com/user-attachments/assets/ee28581a-575b-4ecb-983f-bfbe292fb3a5)

## Additional Context

Add any other context or information that may help in diagnosing the issue.

---

### Example 1

**Title:** Product Search Feature Returns No Results  
**Description:** The product search functionality fails to display any results even for valid search queries.

- **Steps to Reproduce:**
  1. Navigate to the product search bar on the homepage.
  2. Type "Wireless Mouse" into the search field.
  3. Press the Enter key.

- **Expected Behavior:** The system should display a list of products matching "Wireless Mouse."  
- **Actual Behavior:** The message "No results found" appears, regardless of valid input.

---

### Example 2

**Title:** Login Issue with Valid Credentials  
**Description:** Users are experiencing issues logging in, despite entering the correct username and password.

- **Steps to Reproduce:**
  1. Access the login page.
  2. Input a valid username and password.
  3. Click the "Login" button.

- **Expected Behavior:** The user should successfully log in and be redirected to their dashboard.  
- **Actual Behavior:** An error message states, "Invalid credentials," preventing access.

---

Thank you for taking the time to report this issue! We appreciate your help in improving our project.

**Comment by thakuratul2** [comment]
@sezallagwal not needed
