### ISSUE TITLE
UI of login page is not attractive 

### ISSUE THREAD

**Issue by Anjalis14** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#206]
the UI needs to be attractive 
![image](https://github.com/user-attachments/assets/e1e871ca-d3b5-4c8d-8df6-af5a43368611)

**Comment by Anjalis14** [comment]
@saurabhbakolia plz assign me this

**Comment by StrugglerSuryansh** [comment]
@thakuratul2 please asssign this to me

**Comment by thakuratul2** [comment]
@StrugglerSuryansh @Anjalis14 this is not needed yet
