### ISSUE TITLE
SignUp page UI can be modified.

### ISSUE THREAD

**Issue by Priyanshu1035** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#216]
# Issue Report

## Title

UI of SignUp page can be modified.

## Description

The SignUp UI is not looking good.
The boxes of firstname, lastname, pasword, email etc. are not visible which gives it a page like look.
And Add eye icons on password and confirm password.
Add hover effects on create Account and SignIn with Google.

## Expected Behavior

Add boxes for the firstname,lastname
Add hover effects on Create and SignIn with Google.
Add eye icons for password visibility in password and confirm password.

## Screenshots (if applicable)
![scrollme](https://github.com/user-attachments/assets/558d4871-72cc-41e8-bf44-256d0dea935c)

## Additional Context

Kindly assign this to me under GSSOC'24-extd and Hacktoberfest.

---

**Comment by saurabhbakolia** [comment]
Closing as resolved in Pr #239
