### ISSUE TITLE
SignIN page UI modification

### ISSUE THREAD

**Issue by Priyanshu1035** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#219]
## Title

Sign IN Page UI needs slight modification

## Description

The Sign In page seems static and the UI can be made more interesting.
The issue is similar to issue #216 

## Steps to Reproduce the Issue

1. **Action 1:** Go to the home page of scrollme.
2. **Action 2:** Go to the Sign IN page.

## Expected Behavior

Add boxes like structure for input.

## Additional Context

Kindly assign this issue to me under GSSOC-extd24 and Hacktoberfest.

---

**Comment by saurabhbakolia** [comment]
Closing issue as resolved in PR #239
