### ISSUE TITLE
Misaligned Google Sign-In Icon on Login/Sign-In Page

### ISSUE THREAD

**Issue by KAJAL7764** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#221]
#Issue Title:
 Google Icon are not aligned in sign-up and sign-in page.

#Description:
 The Google icon on the Login Page is not aligned properly, and the click functionality to sign in with Google is not working. This affects both the visual appearance and the user experience of the login process.

# Steps to Reproduce the Issue

Action 1: Navigate to the Login/Sign-In Page.
Action 2: find the button or icon labeled "Sign in with Google".
Action 3: Observe the Alignments and Compare with Expected Behavior.

![Screenshot 2024-10-19 170848](https://github.com/user-attachments/assets/eebdd903-22f8-4ecc-981c-4efc9b47b82a)

Please assign me this task i want to work on this projet.
also gives this tag:- lavel-1, gssoc-ext  and hacktoberfest

**Comment by saurabhbakolia** [comment]
Closing issue as resolved in PR #239
