### ISSUE TITLE
Website is not responsive for mobile users

### ISSUE THREAD

**Issue by adityalaxkar123** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#24]
# issue
## website is not responsive for mobile users

**Comment by adityalaxkar123** [comment]
Me a GSSOC'24 extended member can you assign me

**Comment by thakuratul2** [comment]
@adityalaxkar123 assigned

**Comment by DivyaJyothi9** [comment]
Hello! I would like to take on the issue of improving the website's responsiveness for mobile users. Enhancing the mobile experience will make it more user-friendly and accessible across different devices. Please assign this issue to me. Thank you!

**Comment by thakuratul2** [comment]
@DivyaJyothi9 already assigned
