### ISSUE TITLE
Carousel Misalignment and Lack of Functionality on Home Page

### ISSUE THREAD

**Issue by samriddhitiwary** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#27]
# Issue Report

[Provide a concise title for the issue]
Carousel Misalignment and Lack of Functionality on Home Page

## Description
The carousel on the home page is not properly aligned, appears static (not moving automatically), and is hidden on mobile devices. Additionally, when hovering over the product cards, the "SHOP NOW" button does not display a gradient and scales out unexpectedly. These issues are affecting both the desktop and mobile user experience.

## Steps to Reproduce the Issue
Action 1: Open the home page on a desktop browser.
Action 2: Observe the alignment of the carousel and note that it does not move automatically.
Action 3: Switch to a mobile device or responsive design mode and note that the carousel is hidden.
Action 4: Hover over any product card and observe the "SHOP NOW" button. It lacks the expected gradient and scales out.

## Expected Behavior
The carousel should be properly aligned and move automatically.
The carousel should be visible on mobile devices.
The "SHOP NOW" button should have a gradient on hover and scale in smoothly.

## Actual Behavior
The carousel is misaligned and static on desktop.
The carousel is hidden on mobile devices.
The "SHOP NOW" button lacks a gradient on hover and scales out instead of scaling in.

Describe what actually happened. Include any error messages or unexpected results.

## Screenshots (if applicable)
![carousel](https://github.com/user-attachments/assets/a4f9e4ba-c5d6-4686-b91b-0ad8d947a3b2)
![shop](https://github.com/user-attachments/assets/cf8a3327-87f2-48c4-88b6-3dfee31eb7a8)

## Additional Context

This issue impacts the aesthetic appeal and functionality of the home page, potentially affecting user engagement. The design needs adjustments to improve the carousel's alignment, movement, and hover effects for a more seamless user experience.

**Comment by samriddhitiwary** [comment]
@thakuratul2 Could please assign this issue to me under the label of GSSoC-ext and Hacktoberfest also

**Comment by thakuratul2** [comment]
@samriddhitiwary assign

**Comment by samriddhitiwary** [comment]
Thank you I have started working on it

**Comment by samriddhitiwary** [comment]
@thakuratul2 which branch should I fork as the master branch is giving compilation error
![image](https://github.com/user-attachments/assets/88aefb31-5f88-4d6d-95d5-8d3003a2f5f3)

**Comment by thakuratul2** [comment]
@samriddhitiwary develop branch and wait 30 minutes I am reviewing this issue already fixed and develop branch is main branch where you create the PR

**Comment by samriddhitiwary** [comment]
Thanks for the quick reply, I had tried the develop branch also, but the issue still persists.

**Comment by thakuratul2** [comment]
@samriddhitiwary give me some time I will merge the PR into develop branch meanwhile you explore the code

**Comment by samriddhitiwary** [comment]
Sure

**Comment by thakuratul2** [comment]
@samriddhitiwary now you can start working but first pull the fresh code in develop branch after start working

**Comment by samriddhitiwary** [comment]
Thank you I will try it now

**Comment by thakuratul2** [comment]
Yes if any problem occurs please let me know

**Comment by samriddhitiwary** [comment]
sure

**Comment by thakuratul2** [comment]
@samriddhitiwary working?

**Comment by samriddhitiwary** [comment]
![image](https://github.com/user-attachments/assets/2ec9e6bc-c755-440f-b8b4-679d5dcd2ff5)
@thakuratul2  Can you please give me the write access

**Comment by thakuratul2** [comment]
@saurabhbakolia look it

**Comment by saurabhbakolia** [comment]
Hey,  @samriddhitiwary 

Have you created your own fork? if so Try the following mehod.
If you have SSH set up, consider using the SSH URL for the repository instead of the HTTPS URL. This might help you avoid permission issues.
You can change the remote URL to SSH with the following command:
`git remote set-url origin git@github.com:saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE.git
`

**Comment by samriddhitiwary** [comment]
Thank you I will try it

**Comment by samriddhitiwary** [comment]
@saurabhbakolia I had set up SSH key for my git account and I had cloned my repository using SSH Protocol still I'm not able to commit and getting the following error
![image](https://github.com/user-attachments/assets/08984479-05cb-49a0-88be-7ae81b4333c1)

**Comment by samriddhitiwary** [comment]
@thakuratul2 I have completed my task and made the changes but in the src folder there are 2 folders with names Components and components which is giving a lot issue in Window when I am trying to push it to the git.

That's why I am renaming the 'component' folder

https://stackoverflow.com/questions/27749219/working-in-git-with-directories-with-the-same-name-but-different-case-in-windows

**Comment by samriddhitiwary** [comment]
@thakuratul2 @saurabhbakolia I have raised a PR, below is the URL, please review
https://github.com/saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE/pull/53

**Comment by thakuratul2** [comment]
Oky

**Comment by samriddhitiwary** [comment]
@thakuratul2 I have also deleted the "Component" folder since it was duplicate

**Comment by samriddhitiwary** [comment]
@thakuratul2  I have raised a PR again could you please review it

**Comment by thakuratul2** [comment]
@samriddhitiwary merged

**Comment by samriddhitiwary** [comment]
@thakuratul2 thank you

**Comment by samriddhitiwary** [comment]
@thakuratul2 could you please add the gssoc-ext and hacktoberfest labels to the MR also 
![image](https://github.com/user-attachments/assets/0d731df0-efa5-4890-81d4-d2e53728cc45)
