### ISSUE TITLE
[Feature Update] : Adding A Payment Getway 

### ISSUE THREAD

**Issue by Amarjha01** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#29]
# Feature Update

## Title
Payment Getway

## Description
I will add Payment getaway for the user so that when user will click on payment icon on footer section the user will redirect to payment page 

## Steps to Implement this feature
1. I will send user data from frontend to backend calling payment getway.
2. Verify the data sent from frontend and authentication.
3. Hashing and adding salt and key to data to create payload.
4. Creating Payload for API call.
5. calling the Payment Getway API 
6. Send response to the user about payment failed or success

## Expected Behavior
The user should able to make payment 

## Actual Behavior
Static page the user is not able to make payment

## Screenshots (if applicable)
<img width="956" alt="image" src="https://github.com/user-attachments/assets/2d984ca5-5002-4b6c-97f3-ca8c61770f3e">

**Comment by thakuratul2** [comment]
@saurabhbakolia can you please assist them it is need by you

**Comment by Amarjha01** [comment]
@thakuratul2 hello sir I wanted to imliment this feature. Please assign this to me . I will use testing Phonepay payment gateway.  for now I will imliment in footer sectionly later when you pull and update the login logout function as it was assign to someone then I will add this in cart.

**Comment by shreyamaheshwari1** [comment]
@saurabhbakolia hello sit , I am currently working on this issue could you please assign tis to me . I wanted to create a paymemt gateway for smooth transactions.

**Comment by thakuratul2** [comment]
@Amarjha01 please pull the fresh code every time while starting working on it from the develop branch

**Comment by Amarjha01** [comment]
https://github.com/user-attachments/assets/ac4a0a5c-7d99-4bf1-a0d3-e228ea30acc3

Here is demonstration video From my last project. [www.electramart.ninja ](url)

**Comment by Amarjha01** [comment]
> @Amarjha01 please pull the fresh code every time while starting working on it from the develop branch

Is this the branch where all updated code is pulled ?

**Comment by thakuratul2** [comment]
@Amarjha01 in develop branch having fresh code always so make the branch from there

**Comment by thakuratul2** [comment]
@Amarjha01 you can implement only api when I use it after other modified I will give

**Comment by thakuratul2** [comment]
@Amarjha01 I am closing this issue because this is not priority

**Comment by Amarjha01** [comment]
@thakuratul2  @saurabhbakolia  sir can you please change the lavel-1 to level1 or level2 or level3 because its not counted on leaderboard.

**Comment by Amarjha01** [comment]
@thakuratul2 @saurabhbakolia  I'm gonna reopen this issue as add to cart functionality is already implemented.
