### ISSUE TITLE
backend not runnning properly dependency issue

### ISSUE THREAD

**Issue by StrugglerSuryansh** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#46]
# Issue Report

## Title

dependencies issue in backend

## Description

nodemon is need to be installed in the backend , 

## Steps to Reproduce the Issue

npm install nodemon@latest
need to run this command in the backend dir

**Comment by thakuratul2** [comment]
@StrugglerSuryansh assigned

**Comment by thakuratul2** [comment]
@StrugglerSuryansh you not need to close this

**Comment by thakuratul2** [comment]
It will closed by me

**Comment by StrugglerSuryansh** [comment]
okay sorry i was unaware
