### ISSUE TITLE
Add Pull Request MD file into README md

### ISSUE THREAD

**Issue by thakuratul2** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#5]
# Issue Report

## Title

Pull Request is missing from the ReadME md table of contents.

## Description

Could you add the pull request md into the README file and make the link clickable?

**Comment by Rizvi-Faiz** [comment]
Hi @thakuratul2 I can add the pull request md in the README file and also make the link clickable.

could you please assign it to me .

**Comment by Rizvi-Faiz** [comment]
Sir Could you please assign it to me

**Comment by thakuratul2** [comment]
@Rizvi-Faiz Done and please read again the issue description to helping for create PR

**Comment by Rizvi-Faiz** [comment]
yes sir

**Comment by thakuratul2** [comment]
@Rizvi-Faiz Create the proper PR description and follow the guidelines which is provided by the gssoc

**Comment by Rizvi-Faiz** [comment]
@thakuratul2 Sir could you please review my PR.

**Comment by thakuratul2** [comment]
@Rizvi-Faiz checking

**Comment by thakuratul2** [comment]
@Rizvi-Faiz check the comments on PR

**Comment by Amarjha01** [comment]
<img width="645" alt="image" src="https://github.com/user-attachments/assets/818f7d98-df63-44e9-b201-4d8875694e38">

please check you project link is not working.

**Comment by thakuratul2** [comment]
@saurabhbakolia please check it deployed link

**Comment by thakuratul2** [comment]
@Amarjha01 Can you create the issue of this and solve and create PR

**Comment by Amarjha01** [comment]
> @Amarjha01 Can you create the issue of this and solve and create PR

yes sure sir .

**Comment by thakuratul2** [comment]
@Amarjha01 mentioned me as reviewers for PR

**Comment by Amarjha01** [comment]
> @Amarjha01 mentioned me as reviewers for PR

yes off course sir but could you please confirm that this issue is not related to deployment but the code itself.

**Comment by thakuratul2** [comment]
@Amarjha01 This is analysed by you dear. Find why this is not working

**Comment by Amarjha01** [comment]
> @Amarjha01 This is analysed by you dear. Find why this is not working

<img width="463" alt="image" src="https://github.com/user-attachments/assets/387f9f93-cbbe-48b0-8735-4d353b7538f6">
this could be the possible issue and I don't have access to confirm it but let me read readme.md file .

**Comment by thakuratul2** [comment]
@Amarjha01 ya setup the project in the local and see what the issue and please create the issue of it

**Comment by thakuratul2** [comment]
@Rizvi-Faiz have you create the PR again?

**Comment by Amarjha01** [comment]
> @Amarjha01 ya setup the project in the local and see what the issue and please create the issue of it

okay sir

**Comment by saurabhbakolia** [comment]
> @saurabhbakolia please check it deployed link

Yes, I have deployed somewhere else. 
You can use this URL instead: https://www.scrollme.online/

**Comment by thakuratul2** [comment]
@Amarjha01 check the link https://www.scrollme.online/

**Comment by Amarjha01** [comment]
okay sir I was just about to summit issue

**Comment by thakuratul2** [comment]
@Amarjha01 you can explore the code and find issues Nd solve it

**Comment by thakuratul2** [comment]
@Amarjha01 oky create the issue and start working on it
