### ISSUE TITLE
Adding a Dockerfile

### ISSUE THREAD

**Issue by vverma022** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#51]
# Issue Report

## Description

We need to add a Dockerfile to containerize our project, which consists of a React frontend with JavaScript and a Node.js backend with JavaScript. The Dockerfile will allow us to package the application in a container, making it easier to deploy and run in any environment. Both the frontend and backend should be built and run inside the container, with ports exposed for proper communication.

## Steps to Reproduce the Issue

To assist us in understanding and resolving the issue, please outline the steps you took that led to the problem:

1. **Action 1:** Create a Dockerfile in the root of the project.
2. **Action 2:**  Configure the Dockerfile
3. **Action 3:** Build the Docker image using docker build -t my-fullstack-app 

*Feel free to be as detailed as necessary so we can replicate the issue accurately.*

## Expected Behavior

Describe what you expected to happen when following the steps above.

## Actual Behavior

The Docker image should build successfully, and the application (frontend and backend) should run within the container. Accessing localhost:3000 should load the frontend, and localhost:5000 should load the backend.

## Screenshots (if applicable)

If applicable, please attach any relevant screenshots or visual aids that help illustrate the issue.

## Additional Context

Currently, there is no Dockerfile, so the project cannot be containerized or run in a consistent environment across different machines.

**Comment by vverma022** [comment]
Can I be assigned this issue under GSSoC '24 Ext and Hacktoberfest

**Comment by thakuratul2** [comment]
@saurabhbakolia it is needed?

**Comment by vverma022** [comment]
Can help with deployment and other contributors to speed up setup process. The reason for this issue is that it is standard practice.

**Comment by saurabhbakolia** [comment]
@thakuratul2 
I think it will. 

@vverma022 
Please also write steps (`documentation`) to setup using docker.

**Comment by thakuratul2** [comment]
@saurabhbakolia okuuy

**Comment by thakuratul2** [comment]
@vverma022 assigned

**Comment by vverma022** [comment]
There are some issues with the dependencies. 
<img width="1439" alt="Screenshot 2024-10-03 at 3 17 04 PM" src="https://github.com/user-attachments/assets/4905ca60-23e9-4aaf-bb4a-63fe1837043c">


> @thakuratul2 I think it will be helpful.
> 
> @vverma022 Please also write steps (`documentation`) to setup using docker.
