### ISSUE TITLE
[BUG] Compiled Problem in the Frontend

### ISSUE THREAD

**Issue by thakuratul2** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#6]
# Issue Report

## Title

Fix the compiled problem in the frontend

## Description

When the fronted page opens in the localhost the compiled problem occurs and displays the issue module not found.

## Steps to Reproduce the Issue

Simply follow the steps to set up the project in your system and then this problem occurs.

*Please feel free to provide as much detail as necessary so we can reproduce the issue accurately.*

**Comment by Laxmi01345** [comment]
I want to work on this issue. Could you please assign it to me?

**Comment by thakuratul2** [comment]
@Laxmi01345 Done and please create the branch from the develop branch and give the proper description and follow the PR guidelines of gssoc

**Comment by Laxmi01345** [comment]
yes sir

**Comment by saurabhbakolia** [comment]
Closing Issue: 

This issue has been resolved with the merge of pull request #33 , which renames the directory from Components to components (lowercase).

Thanks
