### ISSUE TITLE
Making the Sign in and Register page beautiful and appealing

### ISSUE THREAD

**Issue by 770navyasharma** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#63]
The current design of the register and login pages uses a very basic template with simple form elements. To enhance the overall user experience and align the platform with modern e-commerce standards, these pages can be made more dynamic, sleek, and visually appealing. Improving the design will help attract and retain customers by providing a more engaging and professional look. Also Please add hacktoberfest, gssoc tags with level.

@saurabhbakolia Please assign this issue to me.

<img width="1470" alt="Screenshot 2024-10-03 at 11 51 18 AM" src="https://github.com/user-attachments/assets/1e80d96f-03cb-4c9d-9e18-a8cee3c808a8">
<img width="1470" alt="Screenshot 2024-10-03 at 11 51 37 AM" src="https://github.com/user-attachments/assets/2622ef7f-ef86-4ce2-a6f4-5e09cf0b1032">

**Comment by saurabhbakolia** [comment]
@770navyasharma  assigned.

**Comment by 770navyasharma** [comment]
Please also add gssoc, hacktoberfest and level tags to it.
