### ISSUE TITLE
Add Validation for Username, Firstname, Lastname, and Password Fields

### ISSUE THREAD

**Issue by prakrutipathak** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#64]
# Issue Report

## Title

Add Validation for Username, Firstname, Lastname, and Password Fields

## Description

Currently, when creating an account, the system allows registration with just one character in the username, firstname, and lastname fields. Additionally, there is no password validation to ensure a strong password. I propose adding validation for these fields:

- Username, Firstname, and Lastname Validation: These fields should have a minimum of 2 characters, and should not allow digits in the firstname or lastname.
- Password Validation: The password should meet the following criteria for strength:
- At least 8 characters
- Contains at least one digit
- Contains at least one special character

## Steps to Reproduce the Issue

1. Attempt to register an account with only one character in the username, firstname, or lastname fields. It allows the registration.
2. The system also allows digits in the firstname and lastname.
3. No password validation is in place for ensuring strong passwords.

## Expected Behavior

The system should enforce a minimum of 2 characters in the username, firstname, and lastname, disallowing digits in the firstname and lastname. For the password, it should enforce a minimum of 8 characters, including at least one digit and one special character.

## Actual Behavior

Currently, the form allows registration with just one character in the username, firstname, and lastname, and it also permits digits in the firstname and lastname fields. Additionally, weak passwords are allowed without any validation for length, digits, or special characters.

## Screenshots (if applicable)
![Screenshot 2024-10-03 115253](https://github.com/user-attachments/assets/6a82efe3-8b27-4d97-85be-3ef87fb13178)

## Additional Context
I propose implementing these validations to improve the security and data integrity of the registration process.

@saurabhbakolia Please assign this task to me.

**Comment by saurabhbakolia** [comment]
Yes, it's good for security.

**Comment by prakrutipathak** [comment]
@saurabhbakolia @thakuratul2 Can you please assign me label

**Comment by saurabhbakolia** [comment]
> @saurabhbakolia @thakuratul2 Can you please assign me label gssoc-extd and hacktober

Done!

**Comment by lomash-choudhary** [comment]
@thakuratul2 can you assign this to me please.

**Comment by prakrutipathak** [comment]
@lomash-choudhary I already done this

**Comment by saurabhbakolia** [comment]
Closes PR #77
