### ISSUE TITLE
Forget Password Not working

### ISSUE THREAD

**Issue by krishpathak** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#65]
# Issue Report

## Title

Forget Password Not working

## Description

I’ve noticed that the "Forgot Password" feature isn’t functioning properly. This is critical, as users who forget their passwords risk losing access to their accounts.

It's essential to resolve this issue to ensure a seamless user experience.

## Steps to Reproduce the Issue

1. I will write backend route for forgot password.
2. And further integrate wiith backend.

Thank you for taking the time to report this issue! We appreciate your help in improving our project.

**Comment by saurabhbakolia** [comment]
@krishpathak assigned.

**Comment by gopireddysaikiran** [comment]
iam ready to contribute

**Comment by saurabhbakolia** [comment]
@krishpathak  are you still working on it ?

**Comment by krishpathak** [comment]
@saurabhbakolia yes I had completed the work. I just need to resolve conflicts but I am stuck in some other work. I will surely resolve the confllict by tmrw

**Comment by thakuratul2** [comment]
@gopireddysaikiran assigned tou you
