### ISSUE TITLE
Bug: Password hashing for User privacy is missing

### ISSUE THREAD

**Issue by lomash-choudhary** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#76]
# Issue Report

## Title

Missing Password Hashing for user security

## Description

While I was going through the code base during my first commit is saw that there Password hashing is missing of the user's password due to which if database gets leaked then the users password will be out so to protect that we need password hashing.

## Steps to Reproduce the Issue

1. **Action 1:** Go to Home page and singn-up
2. **Action 2:** Now if you willl check the data base then you will find the password entered by the user is in just plain text.

## Expected Behavior

It was expected that the password will be hashed and then stored in the database to protect user's privacy

## Actual Behavior

Password is getting saved in plain text form instead of hashing the password due to which user's privacy is at risk

## Screenshots 

<img width="842" alt="Screenshot 2024-10-03 at 7 48 47 PM" src="https://github.com/user-attachments/assets/a4d8e84f-efe4-4afc-9159-10ec4bcd8431">

**Comment by lomash-choudhary** [comment]
@thakuratul2 please assign this to me.

**Comment by thakuratul2** [comment]
@lomash-choudhary assigned

**Comment by lomash-choudhary** [comment]
I tried this code by locally connecting with my mongo db cluster it is already hashing the password and its working as expected so this issue does not make sense now.
