### ISSUE TITLE
BUG: Pop-up on the website doesn't allow to scroll through the website without signing-in 

### ISSUE THREAD

**Issue by tanushrigoel** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#78]
## Title

Sign-in Popup Appears on Every Page Load, Forcing Unwanted Sign-in

## Description

When visiting the website, a sign-in popup is immediately triggered, preventing access to the page unless the user provides login credentials. This occurs even though the user is not attempting to sign in, which disrupts normal navigation and user experience.

## Steps to Reproduce the Issue

1. Open the website 
2. The sign-in popup appears automatically upon loading the homepage.
3. The user is prompted to enter a username and password before accessing any part of the website.

## Expected Behavior

The website should load the homepage normally without forcing users to sign in unless they explicitly choose the "Sign In" option from the navigation menu.

## Actual Behavior

The website immediately presents a sign-in popup upon visiting the homepage, preventing access to any other part of the site unless login credentials are provided.

## Additional Context

This issue disrupts user experience by preventing users from exploring the site freely, and can cause frustration, especially for first-time visitors who do not yet have login credentials.

## Screenshots 
![Uploading Screenshot 2024-10-03 211454.png…]()

**Comment by saurabhbakolia** [comment]
Closing this issue as it has already been resolved. Thank you for your contributions!
