### ISSUE TITLE
Adding contact us and FAQ section to the website

### ISSUE THREAD

**Issue by govindumeesala** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#84]
# Issue Report

## Description

Adding contact us section and FAQ section will be great and increases user experience a lot. Allowing users to send queries to owner easily

## Steps to Reproduce the Issue

No contact us and FAQ sections in the website

## Expected Behavior

Having contact us and FAQ sections is great for a website.

## Actual Behavior

No contact us page is present in the website

@thakuratul2 @saurabhbakolia please assign it to me I will work on it

**Comment by AgarwalSneh** [comment]
Can i too work on it?

**Comment by saurabhbakolia** [comment]
@AgarwalSneh  I think it's already completed!
You can explore the website create new issues and contribute to the repo.
