### ISSUE TITLE
BUG Twitter logo to X

### ISSUE THREAD

**Issue by govindumeesala** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#85]
# Issue Report

## Description

Twitter changed its logo to X, we using X logo will be a good practice.

## Expected Behavior

X logo for twitter instead of present old logo

## Actual Behavior

Old logo twitter is present

## Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/e5b5b756-5176-4180-8c99-3af41a5572c4)

## Additional Context

@thakuratul2 @saurabhbakolia Please assign it to me

**Comment by thakuratul2** [comment]
@govindumeesala
