### ISSUE TITLE
Add Automated Greeting Workflow

### ISSUE THREAD

**Issue by harish08102004** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#87]
I propose to create a Github workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greetings will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open - source project. We aim to respond or assign your issue as soon as possible .

Hey @thakuratul2 I can work on this.

**Comment by saurabhbakolia** [comment]
@harish08102004 assigned!

**Comment by harish08102004** [comment]
Hey @thakuratul2 @saurabhbakolia I have raised the Pr for the same please check it and merge it.
Additionally I you need to give authorize for deployment check.

**Comment by saurabhbakolia** [comment]
Hey @harish08102004, 
can you please tell me more about this, what kind of permission do you need?

**Comment by harish08102004** [comment]
Hey If I need to create a PR for this from develop, I need to stash the changes of the master or abort them.
![image](https://github.com/user-attachments/assets/63322f06-8947-4b05-82c4-2c0791834a00)
what should i do.

**Comment by saurabhbakolia** [comment]
@harish08102004, 
Stash your changes, then move to the `develop `branch. Make sure your `develop `branch is up to date. After that, pull your stashed changes and create a new PR

Let me know if you need any help.

**Comment by harish08102004** [comment]
hey @saurabhbakolia https://github.com/saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE/pull/123

I have re raised PR for the same 

Please add label for it and check and merge.

**Comment by harish08102004** [comment]
Hey @saurabhbakolia please add labels for the closed PR.

**Comment by saurabhbakolia** [comment]
Closing this issue as it's fixed in PR #134 .

**Comment by harish08102004** [comment]
Hey @saurabhbakolia I created this issue and raised the PR and got merged, I'm saying please add labels for the pr that got merged - https://github.com/saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE/pull/134.
