### ISSUE TITLE
Bug: text not positioned properly

### ISSUE THREAD

**Issue by Anshuaman2001** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#92]
texts are not positioned properly with image
![Screenshot 2024-10-05 034530](https://github.com/user-attachments/assets/dc143c0c-9429-4b90-beb8-13ad2ba14ee1)

**Comment by saurabhbakolia** [comment]
Hey @Anshuaman2001 
I think the issue is already there, Can you please check it once.

**Comment by Anshuaman2001** [comment]
I checked but this issues doesn't exist .
assign this to me .

**Comment by Anshuaman2001** [comment]
> Hey @Anshuaman2001 I think the issue is already there, Can you please check it once.

I checked but this issues doesn't exist .
assign this to me
