### ISSUE TITLE
[BUG] : Colour Of Product Is Not changing

### ISSUE THREAD

**Issue by Amarjha01** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#94]
# Issue Report

## Title
Colour of product Isn't changing.

## Description
Colour of product is not changing when user select different different colors.

## Steps to Reproduce the Issue
- change the image align to colour selected by user using state management.

## Expected Behavior
- Product Image should change when user select different different color.
- Image should be dynamic.

## Actual Behavior
The image of product is static and not changing when user select different colour.

## Video

https://github.com/user-attachments/assets/b6b39dcd-8e11-4126-b243-d0f362fc99ef

https://github.com/user-attachments/assets/e242dbe1-1c8a-484f-8eb3-df4f2156a80c

@thakuratul2 @saurabhbakolia  sir I would like to work on this issue.

**Comment by saurabhbakolia** [comment]
@Amarjha01 assigned!

**Comment by Amarjha01** [comment]
@saurabhbakolia  sir can you please change the level-2 to level2 or level3 because level-2 will not count in leaderboard.
<img width="802" alt="image" src="https://github.com/user-attachments/assets/4678cbb9-434f-4add-9c36-22acd0d5f2ba">
