### ISSUE TITLE
product page overlapping

### ISSUE THREAD

**Issue by vikas83pal** [saurabhbakolia/SCROLLME--ECOMMERCE-WEBSITE#99]
# Issue Report

## Title

Product Page overlapping
![Screenshot 2024-10-05 171634](https://github.com/user-attachments/assets/2c64ef40-6196-4f29-9e7b-e666ba20f938)

## Description

I can make more improvement to the product page and with interactive and responsive

## Steps to Reproduce the Issue

I Will Make Some What Like This with interactive and responsive
![Screenshot 2024-10-05 171935](https://github.com/user-attachments/assets/afa7e4f6-b2c1-4bcc-bbd9-fcb2b3d77444)

**Comment by thakuratul2** [comment]
@vikas83pal assigned

**Comment by vikas83pal** [comment]
@thakuratul2 where it is the product page
